FROM python:3.14-alpine
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY apps/ /app/apps/
COPY stock_market_game/ /app/stock_market_game/
COPY manage.py /app/manage.py
COPY gunicorn.conf.py /app/gunicorn.conf.py
RUN python manage.py collectstatic --noinput
CMD ["gunicorn", "-c", "gunicorn.conf.py","stock_market_game.asgi:application"]