FROM python:3.14-alpine
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY apps/ /app/apps/
COPY stock_market_game/ /app/stock_market_game/
CMD ["celery", "-A", "stock_market_game", "worker"]