# Generated by Django 6.0 on 2025-12-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
