# Generated by Django 6.0 on 2025-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_canceled_order_canceled_at'),
        ('users', '0002_userstock_available'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userstock',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_user_company'),
        ),
    ]
