# Generated by Django 6.0 on 2025-12-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userstock_unique_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstock',
            old_name='available',
            new_name='blocked',
        ),
    ]
