# Generated by Django 6.0 on 2025-12-17 17:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('isin', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('submarket', models.CharField(max_length=50)),
                ('sector', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25))),
                ('stock_no', models.IntegerField()),
                ('market_value', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_market_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('min_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.IntegerField()),
                ('transactions_no', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_market_data.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_daily_price')],
            },
        ),
    ]
