/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CompanyItem: typeof import('./src/components/CompanyItem.vue')['default']
    CompanyRow: typeof import('./src/components/CompanyRow.vue')['default']
    CreateOrder: typeof import('./src/components/CreateOrder.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OrderCreate: typeof import('./src/components/OrderCreate.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrderSimple: typeof import('./src/components/OrderSimple.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockDashboard: typeof import('./src/components/StockDashboard.vue')['default']
    StockItem: typeof import('./src/components/StockItem.vue')['default']
    StockRow: typeof import('./src/components/StockRow.vue')['default']
  }
}
