/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bucket/': RouteRecordInfo<'/bucket/', '/bucket', Record<never, never>, Record<never, never>>,
    '/bucket/[id]': RouteRecordInfo<'/bucket/[id]', '/bucket/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/company/': RouteRecordInfo<'/company/', '/company', Record<never, never>, Record<never, never>>,
    '/company/[id]': RouteRecordInfo<'/company/[id]', '/company/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/order/': RouteRecordInfo<'/order/', '/order', Record<never, never>, Record<never, never>>,
    '/order/[id]': RouteRecordInfo<'/order/[id]', '/order/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/bucket/index.vue': {
      routes: '/bucket/'
      views: never
    }
    'src/pages/bucket/[id].vue': {
      routes: '/bucket/[id]'
      views: never
    }
    'src/pages/company/index.vue': {
      routes: '/company/'
      views: never
    }
    'src/pages/company/[id].vue': {
      routes: '/company/[id]'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/order/index.vue': {
      routes: '/order/'
      views: never
    }
    'src/pages/order/[id].vue': {
      routes: '/order/[id]'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
