# Generated by Django 5.2.9 on 2025-12-30 18:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('sector', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
                ('stock_no', models.IntegerField()),
                ('market_value', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': '"market"."company"',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('executed_ad', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"market"."transaction"',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(default=None, null=True)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('amount', models.IntegerField()),
                ('available', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company')),
            ],
            options={
                'db_table': '"market"."order"',
            },
        ),
    ]
