# Generated by Django 5.2.9 on 2025-12-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_1', to='market.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_2', to='market.order'),
        ),
    ]
